before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: UeTqWZTGFVE5xr/hYxZmZsSVzLA4ps2ZkCxCNTAg3GRbeOWZ3+a0ybKiZwX4IIqfEszzg1Q5JuzgDnJ0I/5rYv97ArHzseKxOAqKOPohGrANtAsZo2qj6j4Yy/umzPFO8rZZtpihw+9QgbkrO1Gz2uj9m5/WbtRY+Elc4zYD4kW/Css/GB9qpC+abk8ELfxbw4ZSx1rsSI0EGTQMPZC3ocAM6PREdfm8kYiypwWr5ltRDtaAULpu92MvlyTeU9l6m+y4aKlQeqUcPuRF7RplnWOl2loBqh9ozbkKrwgHNRjB13y2VL+d6KSTR7iDnqjQmWa8NvU1Y3xwWWpys49nmpvz+oITP6mBBNpWFOo9Da6Ovo8hEA0HJj5Z78BiQhUAgSZ1sxpkhJ6NVtURy2yPYPxBoIGAs+kfRXdK4uBSPlchT+qEFjBLcSuKmPtLaWk1p3PStGAumrppxWf5OWh3vevS6ZThHK5SfQe5tVwHh6XHuZ0F0IlnfkPbM4NbSaK2q19UbDlqUUTueCCrDxhMmUlvuc3HTgJWQassEqfOLvR0rPtTK73H/fJCO9zDGQ7cFF8GHxb+oe/qv50sBGcUhSQl1s3KDvl3GyLbHsvglj8wQ5ImKT+MXOqB04ITfR5fco5usOVod9v3sNq9fHQpgXoREFKa8Hn8IxnPtjTalsY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
